<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>Phoenix Market City</title>';
echo '<link rel="stylesheet" type="text/css" href="style.css">';
echo '</head>';
echo '<body>';
echo '<div class="hero">';
echo '<div class="logo">';
echo '<img src="logo.png">';
echo '</div>';
echo '<div class="form-box">';
echo '';
echo '<div class="button-box">';
echo '<div id="btn"></div>';
echo '<button type="button" class="toggle-btn" onclick="login()">Log in</button>';
echo '<button type="button" class="toggle-btn" onclick="register()">Register</button>';
echo '';
echo '</div>';
echo '<div class="social-icons">';
echo '<img src="fb.png">';
echo '<img src="twitter.png">';
echo '<img src="google.png">';
echo '</div>';
echo '<form id="login" class="input-group">';
echo '<input type="text" class="input-field" placeholder="User Id" required>';
echo '<input type="text" class="input-field" placeholder="Enter Password" required>';
echo '<input type="checkbox" class="chech-box"><span>Remember Password</span>';
echo '<button type="submit" class="submit-btn">Log In</button>';
echo '</form>';
echo '<form id="register" class="input-group">';
echo '<input type="text" class="input-field" placeholder="User Id" required>';
echo '<input type="email" class="input-field" placeholder="Email Id" required>';
echo '<input type="text" class="input-field" placeholder="Enter Password" required>';
echo '<input type="checkbox" class="chech-box"><span>I agree to the terms & conditions</span>';
echo '<button type="submit" class="submit-btn">Register</button>';
echo '</form>';
echo '</div>';
echo '';
echo '</div>';
echo '<script>';
echo 'var x = document.getElementsByid("login");';
echo 'var y =document.getElementsByid("register");';
echo 'var z = document.getElementsByid("btn");';
echo 'function register()';
echo '{';
echo 'x.style.left="-400px";';
echo 'y.style.left="50px";';
echo 'z.style.left="110px";';
echo '}';
echo 'function login(){';
echo 'x.style.left="50px";';
echo 'y.style.left="450px";';
echo 'z.style.left="0";';
echo '}';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '</script>';
echo '</body>';
echo '</html>';
echo '';
?>
